# Generated by Django 2.1.7 on 2019-04-30 21:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseenvironmentfeatures',
            name='habitat_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DE', 'Development'), ('FE', 'Forest Edge'), ('FG', 'Forest Gap'), ('FI', 'Field'), ('SR', 'Stream/River'), ('WP', 'Wetland/Pond'), ('OT', 'Other')], help_text='Type of environment around the bat house', max_length=2), size=None),
        ),
        migrations.AlterField(
            model_name='housephysicalfeatures',
            name='mounted_on',
            field=models.CharField(choices=[('BD', 'Building'), ('PI', 'On a pole by itself'), ('PB', 'On a pole with another bat house, back to back'), ('TR', 'Tree'), ('OT', 'Other')], help_text='Item which bat house is mounted to', max_length=2),
        ),
        migrations.AlterField(
            model_name='observation',
            name='checked',
            field=models.DateTimeField(help_text='Date and time when the bat house was checked'),
        ),
    ]
