# Generated by Django 2.1.7 on 2019-03-26 02:32

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bathouse', '0003_auto_20190325_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseEnvironmentFeatures',
            fields=[
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bathouse.House')),
                ('habitat_degradation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DU', 'Dumping'), ('ER', 'Erosion'), ('TR', 'Trash'), ('NO', 'None'), ('OT', 'Other')], max_length=2), help_text='Habitat degradation present around the bat house', size=None)),
                ('other_habitat_degradation', models.CharField(blank=True, help_text='Habitat degradation if Other was selected', max_length=255)),
                ('habitat_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DE', 'Development'), ('FE', 'Forest Edge'), ('FG', 'Forest Gap'), ('FI', 'Field'), ('SR', 'Stream/River'), ('WP', 'Wetland/Pond'), ('OT', 'Other')], max_length=2), help_text='Type of environment around the bat house', size=None)),
                ('other_habitat_type', models.CharField(blank=True, help_text='Habitat type if Other was selected', max_length=255)),
                ('man_made_structure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BU', 'Building'), ('BR', 'Bridge'), ('DA', 'Dam'), ('DR', 'Dirt Road'), ('FE', 'Fence'), ('PR', 'Paved Roads'), ('TR', 'Trail'), ('NO', 'None'), ('OT', 'Other')], max_length=2), help_text='Man-made structures present around the bat house', size=None)),
                ('other_man_made_structure', models.CharField(blank=True, help_text='Man-made structures present if Other was selected', max_length=255)),
                ('nearby_geography', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VB', 'Valley or Bottomland Hillside'), ('RI', 'Ridgetop'), ('PL', 'Plane (Flat Area)')], max_length=2), help_text='Nearby geography of the area around the bat house', size=None)),
                ('slope', models.CharField(choices=[('F', 'Flat'), ('G', 'Gentle'), ('U', 'Undulating'), ('S', 'Steep')], help_text='Type of slope the bat house is on', max_length=1)),
                ('tree_type', models.IntegerField(help_text='Types of trees surrounding the bat house', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('day_noise', models.CharField(choices=[('L', 'Loud'), ('M', 'Medium'), ('Q', 'Quiet')], help_text='Noise around the bat house throughout the day', max_length=1)),
                ('night_noise', models.CharField(choices=[('L', 'Loud'), ('M', 'Medium'), ('Q', 'Quiet')], help_text='Noise around the bat house throughout the night', max_length=1)),
                ('noise_disturbance', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BI', 'Businesses/Industry'), ('CA', 'Cars'), ('PR', 'People/Residential'), ('NO', 'None'), ('OT', 'Other')], max_length=2), help_text='Noise disturbances around the bat house', size=None)),
                ('other_noise_disturbance', models.CharField(blank=True, help_text='Noise disturbances if Other was selected', max_length=255)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('night_light_pollution_amount', models.CharField(choices=[('A', 'A lot'), ('M', 'Medium'), ('L', 'Low'), ('N', 'None')], help_text='Light pollution amount at night around the bat house', max_length=1)),
                ('night_light_pollution_consistency', models.CharField(choices=[('T', 'Throughout'), ('I', 'Inconsistent')], help_text='Light pollution consistency at night around the bat house', max_length=1)),
                ('nearest_water_resources', models.CharField(choices=[('CW', 'Coastal Wetland'), ('IW', 'Inland Wetland'), ('LA', 'Lake'), ('PO', 'Pond'), ('RI', 'River'), ('ST', 'Stream'), ('VP', 'Vernal Pool'), ('NO', 'None'), ('OT', 'Other')], help_text='Nearest water resource to the bat house', max_length=2)),
                ('other_nearest_water_resource', models.CharField(blank=True, help_text='Water resource if Other was selected', max_length=255)),
                ('water_resource_distance', models.PositiveIntegerField(help_text='Distance to nearest water resource', validators=[django.core.validators.MinValueValidator(1)])),
                ('water_resource_units', models.CharField(choices=[('FT', 'Feet'), ('KM', 'Kilometers'), ('ME', 'Meters'), ('MI', 'Miles')], help_text='Units of distance to nearest water resource', max_length=2)),
                ('morning_sunlight', models.PositiveIntegerField(help_text='Amount of hours of morning sunlight the bat house receives', validators=[django.core.validators.MinValueValidator(1)])),
                ('afternoon_sunlight', models.PositiveIntegerField(help_text='Amount of hours of afternoon sunlight the bat house         receives', validators=[django.core.validators.MinValueValidator(1)])),
                ('other_features', models.TextField(help_text='Other environmental features not covered')),
            ],
        ),
        migrations.CreateModel(
            name='HousePhysicalFeatures',
            fields=[
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bathouse.House')),
                ('house_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], help_text='Approximate size of the bat house', max_length=1)),
                ('color', models.CharField(choices=[('BL', 'Black'), ('DB', 'Dark brown'), ('MB', 'Medium brown'), ('LB', 'Light brown'), ('TB', 'Tan/Beige'), ('NW', 'Natural wood'), ('WH', 'White'), ('OT', 'Other')], help_text='Color of bat house', max_length=2)),
                ('other_color', models.CharField(blank=True, help_text='Color of bat house if Other is specified', max_length=255)),
                ('chambers', models.PositiveIntegerField(help_text='Number of chambers in bat house', validators=[django.core.validators.MinValueValidator(1)])),
                ('direction', models.CharField(choices=[('NO', 'North'), ('NE', 'Northeast'), ('EA', 'East'), ('SE', 'Southeast'), ('SO', 'South'), ('SW', 'Southwest'), ('WE', 'West'), ('NW', 'Northwest')], help_text='Direction which bat house is facing', max_length=2)),
                ('mounted_on', models.CharField(choices=[('BB', 'Back to back'), ('BD', 'Building'), ('PI', 'Pole by itself'), ('PI', 'Pole with another bat house'), ('TR', 'Tree'), ('OT', 'Other')], help_text='Item which bat house is mounted to', max_length=2)),
                ('other_mounted_on', models.CharField(blank=True, help_text='Mount type if Other is specified', max_length=255)),
                ('ground_height', models.PositiveIntegerField(help_text='Height above the ground surface (in feet)', validators=[django.core.validators.MinValueValidator(1)])),
                ('installed', models.DateField(help_text='Date when the bat house was installed')),
            ],
        ),
        migrations.RemoveField(
            model_name='houseinformation',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='other_property_type',
            field=models.CharField(blank=True, help_text='Property type if Other was selected', max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('ST', 'State'), ('TO', 'Town'), ('SC', 'School'), ('LT', 'Land Trust'), ('PR', 'Private'), ('OT', 'Other')], default='OT', help_text='Property type where bat house is located', max_length=2),
        ),
        migrations.AddField(
            model_name='house',
            name='town_name',
            field=models.CharField(blank=True, help_text='Town where bat house is located', max_length=255, verbose_name='town location'),
        ),
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when House was created'),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Point that indicates where the bat house is located', srid=4326, verbose_name='geographical location'),
        ),
        migrations.AlterField(
            model_name='house',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date when House was updated'),
        ),
        migrations.AlterField(
            model_name='house',
            name='watcher',
            field=models.ForeignKey(help_text='User that provides survey data for the bat house', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HouseInformation',
        ),
    ]
