# Generated by Django 2.1.7 on 2019-03-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bathouse', '0004_auto_20190325_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bathouse.House')),
                ('checked', models.DateTimeField(help_text='Date and when the bat house was checked')),
                ('present', models.BooleanField(help_text='True if bats were there, False otherwise', verbose_name='bat presence')),
                ('occupants', models.IntegerField(blank=True, help_text='Amount of bats present in the bat house')),
                ('acoustic_monitor', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], help_text='Has a bat biologist came to setup acoustic monitoring around             the bat house?', max_length=1)),
                ('notes', models.TextField(blank=True, help_text='Other notes about observations')),
            ],
        ),
    ]
